baseURL = 'https://suthervitch-recipes.github.io/'
locale = 'en-us'
title = 'Suthervitch Recipes'
theme = 'PaperMod'
summaryLength = 0

[taxonomies]
    tag = "tags"
    category = "categories"
    # REGISTERING STARS AS A TAXONOMY
    star = "stars"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    name = "Search"
    url = "search/"
    weight = 10

[params]
    showFullContents = false
    description = true
    disableSpecial1stPost = true
    showDescription = true

    [params.searchConfig]
        from_frontmatter = true
        include_content = true
        # ADDED 'STARS' TO SEARCH FIELDS
        fields = ["title", "content", "tags", "description", "categories", "stars"]
