baseURL = 'https://suthervitch-recipes.github.io/'
locale = 'en-us'
title = 'Suthervitch Recipes'
theme = 'PaperMod'
summaryLength = 0

[taxonomies]
    tag = "tags"
    category = "categories"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    name = "Search"
    url = "search/"
    weight = 10

[params]
    showFullContents = false
    description = true
    disableSpecial1stPost = true
    showDescription = true
[params.searchConfig]
    from_frontmatter = true
    include_content = true
    # This is the critical line to include tags in the search
    fields = ["title", "content", "tags", "description", "categories"]
