backend:
  name: github
  repo: suthervitch-recipes/suthervitch-recipes.github.io
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Short Description", name: "description", widget: "text" }
      - label: "Featured Image"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - { label: "Image", name: "image", widget: "image", required: false, default: "" }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
          - { label: "Caption", name: "caption", widget: "string", required: false }
      - { label: "Ingredients", name: "ingredients", widget: "list", summary: "{{fields.item}}" }
      - { label: "Instructions", name: "body", widget: "markdown" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        summary: "{{fields.tag}}" # This shows the tag name even when the row is closed
        field: { label: "Tag", name: "tag", widget: "string" }
